services:
  postgres:
    image: postgres:16-alpine
    container_name: menu-db
    environment:
      POSTGRES_DB: menu_db
      POSTGRES_USER: menu_user
      POSTGRES_PASSWORD: menu_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U menu_user -d menu_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - menu-network

  app:
    build: .
    container_name: menu-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/menu_db
      SPRING_DATASOURCE_USERNAME: menu_user
      SPRING_DATASOURCE_PASSWORD: menu_pass
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - menu-network

networks:
  menu-network:
    driver: bridge

volumes:
  pgdata:
